import type { Customer, Layout, Reservation, Table, TimeSlot } from "@/types/reservation"

// Horários disponíveis
export const timeSlots: TimeSlot[] = [
  { id: "1", time: "12:00", available: true },
  { id: "2", time: "12:30", available: true },
  { id: "3", time: "13:00", available: true },
  { id: "4", time: "13:30", available: true },
  { id: "5", time: "14:00", available: true },
  { id: "6", time: "19:00", available: true },
  { id: "7", time: "19:30", available: true },
  { id: "8", time: "20:00", available: true },
  { id: "9", time: "20:30", available: true },
  { id: "10", time: "21:00", available: true },
  { id: "11", time: "21:30", available: true },
  { id: "12", time: "22:00", available: true },
]

// Mesas do The OX Room
export const theOxRoomTables: Table[] = [
  // Área principal
  {
    id: "tor-1",
    number: 1,
    size: 2,
    status: "available",
    x: 100,
    y: 100,
    width: 60,
    height: 60,
    shape: "circle",
    area: "main",
    location: "theoxroom",
  },
  {
    id: "tor-2",
    number: 2,
    size: 2,
    status: "available",
    x: 200,
    y: 100,
    width: 60,
    height: 60,
    shape: "circle",
    area: "main",
    location: "theoxroom",
  },
  {
    id: "tor-3",
    number: 3,
    size: 4,
    status: "available",
    x: 300,
    y: 100,
    width: 80,
    height: 80,
    shape: "circle",
    area: "main",
    location: "theoxroom",
  },
  {
    id: "tor-4",
    number: 4,
    size: 4,
    status: "available",
    x: 400,
    y: 100,
    width: 80,
    height: 80,
    shape: "circle",
    area: "main",
    location: "theoxroom",
  },

  // Área da janela
  {
    id: "tor-5",
    number: 5,
    size: 2,
    status: "available",
    x: 100,
    y: 200,
    width: 60,
    height: 60,
    shape: "circle",
    area: "window",
    location: "theoxroom",
  },
  {
    id: "tor-6",
    number: 6,
    size: 4,
    status: "available",
    x: 200,
    y: 200,
    width: 80,
    height: 80,
    shape: "circle",
    area: "window",
    location: "theoxroom",
  },
  {
    id: "tor-7",
    number: 7,
    size: 4,
    status: "available",
    x: 300,
    y: 200,
    width: 80,
    height: 80,
    shape: "circle",
    area: "window",
    location: "theoxroom",
  },

  // Área privativa
  {
    id: "tor-8",
    number: 8,
    size: 6,
    status: "available",
    x: 100,
    y: 300,
    width: 120,
    height: 80,
    shape: "rectangle",
    area: "private",
    location: "theoxroom",
  },
  {
    id: "tor-9",
    number: 9,
    size: 8,
    status: "available",
    x: 250,
    y: 300,
    width: 160,
    height: 80,
    shape: "rectangle",
    area: "private",
    location: "theoxroom",
  },

  // Área externa
  {
    id: "tor-10",
    number: 10,
    size: 4,
    status: "available",
    x: 100,
    y: 400,
    width: 80,
    height: 80,
    shape: "circle",
    area: "outdoor",
    location: "theoxroom",
  },
  {
    id: "tor-11",
    number: 11,
    size: 4,
    status: "available",
    x: 200,
    y: 400,
    width: 80,
    height: 80,
    shape: "circle",
    area: "outdoor",
    location: "theoxroom",
  },
  {
    id: "tor-12",
    number: 12,
    size: 6,
    status: "available",
    x: 300,
    y: 400,
    width: 120,
    height: 80,
    shape: "rectangle",
    area: "outdoor",
    location: "theoxroom",
  },

  // Área do bar
  {
    id: "tor-13",
    number: 13,
    size: 2,
    status: "available",
    x: 100,
    y: 500,
    width: 60,
    height: 60,
    shape: "circle",
    area: "bar",
    location: "theoxroom",
  },
  {
    id: "tor-14",
    number: 14,
    size: 2,
    status: "available",
    x: 200,
    y: 500,
    width: 60,
    height: 60,
    shape: "circle",
    area: "bar",
    location: "theoxroom",
  },
  {
    id: "tor-15",
    number: 15,
    size: 2,
    status: "available",
    x: 300,
    y: 500,
    width: 60,
    height: 60,
    shape: "circle",
    area: "bar",
    location: "theoxroom",
  },
]

// Mesas do OX Steakfish
export const oxSteakfishTables: Table[] = [
  // Área principal
  {
    id: "osf-1",
    number: 1,
    size: 2,
    status: "available",
    x: 100,
    y: 100,
    width: 60,
    height: 60,
    shape: "circle",
    area: "main",
    location: "oxsteakfish",
  },
  {
    id: "osf-2",
    number: 2,
    size: 2,
    status: "available",
    x: 200,
    y: 100,
    width: 60,
    height: 60,
    shape: "circle",
    area: "main",
    location: "oxsteakfish",
  },
  {
    id: "osf-3",
    number: 3,
    size: 4,
    status: "available",
    x: 300,
    y: 100,
    width: 80,
    height: 80,
    shape: "circle",
    area: "main",
    location: "oxsteakfish",
  },
  {
    id: "osf-4",
    number: 4,
    size: 4,
    status: "available",
    x: 400,
    y: 100,
    width: 80,
    height: 80,
    shape: "circle",
    area: "main",
    location: "oxsteakfish",
  },

  // Área da janela
  {
    id: "osf-5",
    number: 5,
    size: 2,
    status: "available",
    x: 100,
    y: 200,
    width: 60,
    height: 60,
    shape: "circle",
    area: "window",
    location: "oxsteakfish",
  },
  {
    id: "osf-6",
    number: 6,
    size: 4,
    status: "available",
    x: 200,
    y: 200,
    width: 80,
    height: 80,
    shape: "circle",
    area: "window",
    location: "oxsteakfish",
  },
  {
    id: "osf-7",
    number: 7,
    size: 4,
    status: "available",
    x: 300,
    y: 200,
    width: 80,
    height: 80,
    shape: "circle",
    area: "window",
    location: "oxsteakfish",
  },

  // Área privativa
  {
    id: "osf-8",
    number: 8,
    size: 6,
    status: "available",
    x: 100,
    y: 300,
    width: 120,
    height: 80,
    shape: "rectangle",
    area: "private",
    location: "oxsteakfish",
  },
  {
    id: "osf-9",
    number: 9,
    size: 8,
    status: "available",
    x: 250,
    y: 300,
    width: 160,
    height: 80,
    shape: "rectangle",
    area: "private",
    location: "oxsteakfish",
  },
  {
    id: "osf-10",
    number: 10,
    size: 10,
    status: "available",
    x: 450,
    y: 300,
    width: 200,
    height: 80,
    shape: "rectangle",
    area: "private",
    location: "oxsteakfish",
  },

  // Área externa
  {
    id: "osf-11",
    number: 11,
    size: 4,
    status: "available",
    x: 100,
    y: 400,
    width: 80,
    height: 80,
    shape: "circle",
    area: "outdoor",
    location: "oxsteakfish",
  },
  {
    id: "osf-12",
    number: 12,
    size: 4,
    status: "available",
    x: 200,
    y: 400,
    width: 80,
    height: 80,
    shape: "circle",
    area: "outdoor",
    location: "oxsteakfish",
  },
  {
    id: "osf-13",
    number: 13,
    size: 6,
    status: "available",
    x: 300,
    y: 400,
    width: 120,
    height: 80,
    shape: "rectangle",
    area: "outdoor",
    location: "oxsteakfish",
  },

  // Área do bar
  {
    id: "osf-14",
    number: 14,
    size: 2,
    status: "available",
    x: 100,
    y: 500,
    width: 60,
    height: 60,
    shape: "circle",
    area: "bar",
    location: "oxsteakfish",
  },
  {
    id: "osf-15",
    number: 15,
    size: 2,
    status: "available",
    x: 200,
    y: 500,
    width: 60,
    height: 60,
    shape: "circle",
    area: "bar",
    location: "oxsteakfish",
  },
  {
    id: "osf-16",
    number: 16,
    size: 2,
    status: "available",
    x: 300,
    y: 500,
    width: 60,
    height: 60,
    shape: "circle",
    area: "bar",
    location: "oxsteakfish",
  },
  {
    id: "osf-17",
    number: 17,
    size: 2,
    status: "available",
    x: 400,
    y: 500,
    width: 60,
    height: 60,
    shape: "circle",
    area: "bar",
    location: "oxsteakfish",
  },
]

// Layouts
export const layouts: Layout[] = [
  {
    id: "theoxroom-layout",
    name: "The OX Room",
    areas: [
      { id: "tor-main", name: "Salão Principal", tables: theOxRoomTables.filter((t) => t.area === "main") },
      { id: "tor-window", name: "Área da Janela", tables: theOxRoomTables.filter((t) => t.area === "window") },
      { id: "tor-private", name: "Salas Privativas", tables: theOxRoomTables.filter((t) => t.area === "private") },
      { id: "tor-outdoor", name: "Área Externa", tables: theOxRoomTables.filter((t) => t.area === "outdoor") },
      { id: "tor-bar", name: "Bar", tables: theOxRoomTables.filter((t) => t.area === "bar") },
    ],
    location: "theoxroom",
  },
  {
    id: "oxsteakfish-layout",
    name: "OX Steakfish",
    areas: [
      { id: "osf-main", name: "Salão Principal", tables: oxSteakfishTables.filter((t) => t.area === "main") },
      { id: "osf-window", name: "Área da Janela", tables: oxSteakfishTables.filter((t) => t.area === "window") },
      { id: "osf-private", name: "Salas Privativas", tables: oxSteakfishTables.filter((t) => t.area === "private") },
      { id: "osf-outdoor", name: "Área Externa", tables: oxSteakfishTables.filter((t) => t.area === "outdoor") },
      { id: "osf-bar", name: "Bar", tables: oxSteakfishTables.filter((t) => t.area === "bar") },
    ],
    location: "oxsteakfish",
  },
]

// Clientes
export const customers: Customer[] = [
  {
    id: "c1",
    name: "João Silva",
    email: "joao.silva@email.com",
    phone: "(11) 98765-4321",
    reservations: ["r1"],
    vip: false,
  },
  {
    id: "c2",
    name: "Maria Oliveira",
    email: "maria.oliveira@email.com",
    phone: "(11) 91234-5678",
    reservations: ["r2"],
    vip: true,
    notes: "Prefere mesa próxima à janela",
  },
  {
    id: "c3",
    name: "Carlos Santos",
    email: "carlos.santos@email.com",
    phone: "(11) 99876-5432",
    reservations: ["r3"],
    vip: false,
  },
]

// Reservas
export const reservations: Reservation[] = [
  {
    id: "r1",
    tableId: "tor-3",
    customerId: "c1",
    customerName: "João Silva",
    customerEmail: "joao.silva@email.com",
    customerPhone: "(11) 98765-4321",
    date: "2025-05-20",
    time: "20:00",
    partySize: 4,
    status: "confirmed",
    createdAt: "2025-05-15T14:30:00Z",
    updatedAt: "2025-05-15T14:30:00Z",
    location: "theoxroom",
  },
  {
    id: "r2",
    tableId: "tor-6",
    customerId: "c2",
    customerName: "Maria Oliveira",
    customerEmail: "maria.oliveira@email.com",
    customerPhone: "(11) 91234-5678",
    date: "2025-05-20",
    time: "20:30",
    partySize: 2,
    specialRequests: "Mesa próxima à janela, comemorando aniversário",
    status: "confirmed",
    createdAt: "2025-05-14T10:15:00Z",
    updatedAt: "2025-05-14T10:15:00Z",
    location: "theoxroom",
  },
  {
    id: "r3",
    tableId: "osf-8",
    customerId: "c3",
    customerName: "Carlos Santos",
    customerEmail: "carlos.santos@email.com",
    customerPhone: "(11) 99876-5432",
    date: "2025-05-20",
    time: "19:30",
    partySize: 6,
    specialRequests: "Grupo de negócios, precisa de privacidade",
    status: "confirmed",
    createdAt: "2025-05-16T09:45:00Z",
    updatedAt: "2025-05-16T09:45:00Z",
    location: "oxsteakfish",
  },
]
